### ISSUE TITLE
Structs implementing gen:equal+hash not being handled properly

### ISSUE THREAD

**Issue by dkvasnicka** [racket/racklog#16]
Hey there, first of all thanks for this library, it's cool to be able to mix Prolog style code and Racket :)
I'm trying to build predicates using structs as opposed to primitive values as shown in the docs and I'm getting this:

```scheme
> (struct bag (color content cnt) #:transparent
  #:methods gen:equal+hash
  [(define (equal-proc b1 b2 recursive-equal?)
     (equal? (bag-color b1) (bag-color b2)))
   (define (hash-proc bag __)
     (equal-hash-code bag))
   (define (hash2-proc bag __)
     (equal-secondary-hash-code bag))])
> (%which (x) (%and (%= x (bag 1 '() 0)) (%member x (list (bag 1 '() 0)))))
((x . #(struct:bag 1 () 0)))
> (%which (x) (%and (%= x (bag 1 '() 0)) (%member x (list (bag 1 '() 1)))))
#f
```

I need the second `%which` to return a value as well because I defined that bags should only be compared using their color. Is this a bug or a desired feature? I was briefly looking into `unify.rkt` and thought I saw you using `equal?`, which should work correctly in this scenario, right?

**Comment by jeapostrophe** [comment]
I don't know what the right solution to this is.

Right now, `racklog` divides structs into two categories: "atomic" struct and "compound" structs. If they are "atomic", then they are compared with `eqv?` in `ident?` and `equal?` in `unify`. If they are "compound", then all of their fields are inspected; essentially they are treated like lists.

What makes something "atomic" versus "compound"? Technically if `struct-info` gives all the information back about the struct instance [1], which basically means if the struct is `#:transparent`.

The idea is that if `racklog` has access to the internals of the structure, then it is not an abstract type (i.e. it is not something that hides its representation and implements an external interface), so `racklog` expects you to want it to inspect inside it.

I believe that your code will work if you remove `#:transparent` from your `struct` definition. I believe that the current `racklog` behavior is sensible, but that's, of course, self-serving on my part ;)

If I were to speculate wildly about why you have `#:transparent` in your program, maybe it's just because you want to be able to print out the instance nicely; that's why I use it in the majority of cases, but you are actually getting a lot more than that when you use `#:transparent`.

1. https://docs.racket-lang.org/reference/inspectors.html#%28def._%28%28quote._~23~25kernel%29._struct-info%29%29

**Comment by dkvasnicka** [comment]
Thanks for the insights! Yes, disabling transparency did the trick. I think your reasoning & design actually make sense. As you said I too use `#:transparent` basically only to get nice visual presentation for free but the truth probably is that this feature was not meant for that. I guess the correct way to go about it is to implement `gen:custom-write` - which I did and now have my cake and can eat it too :)
